name: Container
on: [push]

# jobs:
#   node_docker:
#     runs-on: ubuntu-latest
#     container:                      ######## define the docker container so that instead of running directly on the ubuntu, it will run ina container inside ubuntu
#                                     ###### get the image from ducker hub (container:docker hub image name: image)
#       image: node:13.5.0-alpine3.10
#     steps:
#       - name: Log node version  
#         run: |
#           node -v
#           cat /etc/os-release

######### below line of code to run multiple containers,
jobs: 
  node-docker:
    runs-on: ubuntu-latest
    services:                   
      app:                                #######1st container- for the node-api image from docker hub
        image: alialaa17/node-api         #### image name
        ports:
          - 3001:3000
      mongo:                              ####### 2nd container for the mongo db from the docker hub
        image: mongo                      #### image name
        ports:
          - "27017:27017"
    steps:
      - name: Post a user
      ####### below line of code for a post request to create a user 
        run: 'curl -X POST http://localhost:3001/api/user -H ''Content-Type: application/json'' -d ''{"username": "hello","address": "dwded"}'''
      - name: Get Users
        run: curl http://localhost:3001/api/users

#### creating a job to run containers in individual docker steps
  docker-steps:    
    runs-on: ubuntu-latest
    container:
      image: node:10.18.0-jessie            ##### specifying a node image for the container
    steps:
      - name: log node version
        run: node -v                        ##### logging the node version
      - name: Step with docker              ##### another step for specifying another docker image
        uses: docker://node:12.14.1-alpine3.10    ##### this overwrites the previous doc. image specified for the container
        with:
          entrypoint: "/bin/echo"            ##### specifying some commands to be run on start of the docker container
          args: "Hello World"                ##### argument to be passed like th CMD
      - name: Log node version               ##### another individual doc. step
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: /usr/local/bin/node     ##### specifying some commands to be run on start of the docker container
          args: -v                            ##### here the command is to log the version of the node from the usr/local/bin file where the node gets installed

###### instaed of specifying the scripts in in ENTRYPOINT, run those scripts from a script file, 1st create afile and give permission chmod +x
      - uses: actions/checkout@v1
      - name: Run a script
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: ./script.sh
          args: "Some test string"