name: Matrix 
#on: push 
on: pull_request        ##### to make sure it wont run everytime you push to git

jobs: 
 node-version:
    strategy:                                 #####applying strategy for running node likr versions and the os where to run
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest] 
        node_version: [6, 8, 10]
        include:                    ####include - mostly used to pass or set any variables for specific strategy which can be used later
          - os: ubuntu-latest
            node_version: 8
            is_ubuntu_8: "true"
        exclude:                    ##### to exclude, here exclude to run node on certain os and certain version
          - os: ubuntu-latest
            node_version: 6
          - os: macos-latest
            node_version: 8
  #node-version:
    #runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
    env: 
      IS_UBUNTU_8: ${{ matrix.is_ubuntu_8 }} ##### setting env. var from include strategy
    steps: 
      - name: Log node version 
        run: node -v
      - uses: actions/setup-node@v1
        with:
          #node-version: 6
          node-version: ${{ matrix.node_version }}
      - name: Log node version 
        run: |
          node -v
          echo $IS_UBUNTU_8   ##### in above scenario the variable will get set only if os is ubuntu and node version is 8
